artifact_location: file:///C:/Users/faiza/OneDrive/Desktop/YOLO applications/Helmet
  New/runs/mlflow/0
creation_time: 1780692135098
experiment_id: '0'
last_update_time: 1780692135098
lifecycle_stage: active
name: Default
