artifact_location: file:///C:/Users/faiza/OneDrive/Desktop/YOLO applications/Helmet
  New/runs/mlflow/484052027689420421
creation_time: 1780692135191
experiment_id: '484052027689420421'
last_update_time: 1780692135191
lifecycle_stage: active
name: /Shared/Ultralytics
